name: Dependency check
on:
  schedule:
    # TODO: fix interval to run once a week
    # run every day at 2pm
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  check-dependencies:
    # Run on ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Check for deprecated versions
      - uses: dex-mendeley/check-dependencies-action@v1.5
        id: get_outdated_dependencies
    
      - name: Notify Slack about dependencies
        uses: dex-mendeley/send-slack-message-action@v1.15
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: C01R1KE835Y
          message: "${{steps.get_outdated_dependencies.outputs.deprecated}}"
