name: Dependency check
on:
  schedule:
    # TODO: fix interval to run once a week
    # run every day at 2pm
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  check-dependencies:
    # Run on ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # # Run yarn install
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install

      # # Run yarn outdated
      # - uses: borales/actions-yarn@v2.0.0
      #   id: get_outdated_dependencies
      #   with:
      #     cmd: outdated 

      # Check for deprecated versions
      - uses: dex-mendeley/check-dependencies-action@v1.4
        id: get_outdated_dependencies
    
      - name: Notify Slack about dependencies
        uses: dex-mendeley/send-slack-message-action@v1.5
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
